/**
 * 나라 목록 — 유엔 회원국 193개 + 바티칸·팔레스타인 (유엔 옵서버)
 *
 * 출처: 위키데이터 (https://www.wikidata.org, CC0) 에서 한 번 뽑아 표기를 다듬었다.
 * - name: 흔히 쓰는 이름 (조선민주주의인민공화국 → 북한)
 * - capital: 수도 문제에 쓰는 수도. null 이면 수도 문제에서 뺀다
 *   (수도 논란: 이스라엘·팔레스타인 / 수도가 불분명: 적도 기니·나우루 /
 *    수도 이름에 나라 이름이 들어 있어 너무 쉬움: 싱가포르·멕시코시티 등)
 *   수도가 여럿인 나라는 대표 수도 하나 (인도네시아 자카르타, 볼리비아 수크레 등)
 * - continent: 오답 보기를 같은 대륙에서 고를 때 쓴다
 * - easy: '쉬움' 난이도에 나오는 잘 알려진 나라
 * 국기 그림은 flags/<code>.svg (flag-icons, MIT — flags/LICENSE)
 */
export interface Country {
  /** ISO 3166-1 alpha-2 (소문자) — 국기 파일 이름 */
  code: string;
  name: string;
  capital: string | null;
  continent: string;
  easy?: boolean;
}

export const COUNTRIES: readonly Country[] = [
  { code: 'gh', name: '가나', capital: '아크라', continent: '아프리카', easy: true },
  { code: 'ga', name: '가봉', capital: '리브르빌', continent: '아프리카' },
  { code: 'gy', name: '가이아나', capital: '조지타운', continent: '남아메리카' },
  { code: 'gm', name: '감비아', capital: '반줄', continent: '아프리카' },
  { code: 'gt', name: '과테말라', capital: null, continent: '북아메리카' },
  { code: 'gd', name: '그레나다', capital: '세인트조지스', continent: '북아메리카' },
  { code: 'gr', name: '그리스', capital: '아테네', continent: '유럽', easy: true },
  { code: 'gn', name: '기니', capital: '코나크리', continent: '아프리카' },
  { code: 'gw', name: '기니비사우', capital: '비사우', continent: '아프리카' },
  { code: 'na', name: '나미비아', capital: '빈트후크', continent: '아프리카' },
  { code: 'nr', name: '나우루', capital: null, continent: '오세아니아' },
  { code: 'ng', name: '나이지리아', capital: '아부자', continent: '아프리카', easy: true },
  { code: 'ss', name: '남수단', capital: '주바', continent: '아프리카' },
  {
    code: 'za',
    name: '남아프리카 공화국',
    capital: '프리토리아',
    continent: '아프리카',
    easy: true,
  },
  { code: 'nl', name: '네덜란드', capital: '암스테르담', continent: '유럽', easy: true },
  { code: 'np', name: '네팔', capital: '카트만두', continent: '아시아' },
  { code: 'no', name: '노르웨이', capital: '오슬로', continent: '유럽', easy: true },
  { code: 'nz', name: '뉴질랜드', capital: '웰링턴', continent: '오세아니아', easy: true },
  { code: 'ne', name: '니제르', capital: '니아메', continent: '아프리카' },
  { code: 'ni', name: '니카라과', capital: '마나과', continent: '북아메리카' },
  { code: 'kr', name: '대한민국', capital: '서울', continent: '아시아', easy: true },
  { code: 'dk', name: '덴마크', capital: '코펜하겐', continent: '유럽', easy: true },
  { code: 'do', name: '도미니카 공화국', capital: '산토도밍고', continent: '북아메리카' },
  { code: 'dm', name: '도미니카 연방', capital: '로조', continent: '북아메리카' },
  { code: 'de', name: '독일', capital: '베를린', continent: '유럽', easy: true },
  { code: 'tl', name: '동티모르', capital: '딜리', continent: '아시아' },
  { code: 'la', name: '라오스', capital: '비엔티안', continent: '아시아' },
  { code: 'lr', name: '라이베리아', capital: '몬로비아', continent: '아프리카' },
  { code: 'lv', name: '라트비아', capital: '리가', continent: '유럽' },
  { code: 'ru', name: '러시아', capital: '모스크바', continent: '아시아', easy: true },
  { code: 'lb', name: '레바논', capital: '베이루트', continent: '아시아' },
  { code: 'ls', name: '레소토', capital: '마세루', continent: '아프리카' },
  { code: 'ro', name: '루마니아', capital: '부쿠레슈티', continent: '유럽' },
  { code: 'lu', name: '룩셈부르크', capital: null, continent: '유럽' },
  { code: 'rw', name: '르완다', capital: '키갈리', continent: '아프리카' },
  { code: 'ly', name: '리비아', capital: '트리폴리', continent: '아프리카' },
  { code: 'lt', name: '리투아니아', capital: '빌뉴스', continent: '유럽' },
  { code: 'li', name: '리히텐슈타인', capital: '파두츠', continent: '유럽' },
  { code: 'mg', name: '마다가스카르', capital: '안타나나리보', continent: '아프리카' },
  { code: 'mh', name: '마셜 제도', capital: '마주로', continent: '오세아니아' },
  { code: 'mw', name: '말라위', capital: '릴롱궤', continent: '아프리카' },
  { code: 'my', name: '말레이시아', capital: '쿠알라룸푸르', continent: '아시아', easy: true },
  { code: 'ml', name: '말리', capital: '바마코', continent: '아프리카' },
  { code: 'mx', name: '멕시코', capital: null, continent: '북아메리카', easy: true },
  { code: 'mc', name: '모나코', capital: null, continent: '유럽' },
  { code: 'ma', name: '모로코', capital: '라바트', continent: '아프리카', easy: true },
  { code: 'mu', name: '모리셔스', capital: '포트루이스', continent: '아프리카' },
  { code: 'mr', name: '모리타니', capital: '누악쇼트', continent: '아프리카' },
  { code: 'mz', name: '모잠비크', capital: '마푸투', continent: '아프리카' },
  { code: 'me', name: '몬테네그로', capital: '포드고리차', continent: '유럽' },
  { code: 'md', name: '몰도바', capital: '키시너우', continent: '유럽' },
  { code: 'mv', name: '몰디브', capital: '말레', continent: '아시아' },
  { code: 'mt', name: '몰타', capital: '발레타', continent: '유럽' },
  { code: 'mn', name: '몽골', capital: '울란바타르', continent: '아시아', easy: true },
  { code: 'us', name: '미국', capital: '워싱턴 D.C.', continent: '북아메리카', easy: true },
  { code: 'mm', name: '미얀마', capital: '네피도', continent: '아시아' },
  { code: 'fm', name: '미크로네시아 연방', capital: '팔리키르', continent: '오세아니아' },
  { code: 'vu', name: '바누아투', capital: '포트빌라', continent: '오세아니아' },
  { code: 'bh', name: '바레인', capital: '마나마', continent: '아시아' },
  { code: 'bb', name: '바베이도스', capital: '브리지타운', continent: '북아메리카' },
  { code: 'va', name: '바티칸', capital: null, continent: '유럽' },
  { code: 'bs', name: '바하마', capital: '나소', continent: '북아메리카' },
  { code: 'bd', name: '방글라데시', capital: '다카', continent: '아시아' },
  { code: 'bj', name: '베냉', capital: '포르토노보', continent: '아프리카' },
  { code: 've', name: '베네수엘라', capital: '카라카스', continent: '남아메리카' },
  { code: 'vn', name: '베트남', capital: '하노이', continent: '아시아', easy: true },
  { code: 'be', name: '벨기에', capital: '브뤼셀', continent: '유럽', easy: true },
  { code: 'by', name: '벨라루스', capital: '민스크', continent: '유럽' },
  { code: 'bz', name: '벨리즈', capital: '벨모판', continent: '북아메리카' },
  { code: 'ba', name: '보스니아 헤르체고비나', capital: '사라예보', continent: '유럽' },
  { code: 'bw', name: '보츠와나', capital: '가보로네', continent: '아프리카' },
  { code: 'bo', name: '볼리비아', capital: '수크레', continent: '남아메리카' },
  { code: 'bi', name: '부룬디', capital: '기테가', continent: '아프리카' },
  { code: 'bf', name: '부르키나파소', capital: '와가두구', continent: '아프리카' },
  { code: 'bt', name: '부탄', capital: '팀부', continent: '아시아' },
  { code: 'mk', name: '북마케도니아', capital: '스코페', continent: '유럽' },
  { code: 'kp', name: '북한', capital: '평양', continent: '아시아', easy: true },
  { code: 'bg', name: '불가리아', capital: '소피아', continent: '유럽' },
  { code: 'br', name: '브라질', capital: null, continent: '남아메리카', easy: true },
  { code: 'bn', name: '브루나이', capital: '반다르스리브가완', continent: '아시아' },
  { code: 'ws', name: '사모아', capital: '아피아', continent: '오세아니아' },
  { code: 'sa', name: '사우디아라비아', capital: '리야드', continent: '아시아', easy: true },
  { code: 'sm', name: '산마리노', capital: null, continent: '유럽' },
  { code: 'st', name: '상투메 프린시페', capital: null, continent: '아프리카' },
  { code: 'sn', name: '세네갈', capital: '다카르', continent: '아프리카', easy: true },
  { code: 'rs', name: '세르비아', capital: '베오그라드', continent: '유럽' },
  { code: 'sc', name: '세이셸', capital: '빅토리아', continent: '아프리카' },
  { code: 'lc', name: '세인트루시아', capital: '캐스트리스', continent: '북아메리카' },
  { code: 'vc', name: '세인트빈센트 그레나딘', capital: '킹스타운', continent: '북아메리카' },
  { code: 'kn', name: '세인트키츠 네비스', capital: '바스테르', continent: '북아메리카' },
  { code: 'so', name: '소말리아', capital: '모가디슈', continent: '아프리카' },
  { code: 'sb', name: '솔로몬 제도', capital: '호니아라', continent: '오세아니아' },
  { code: 'sd', name: '수단', capital: '하르툼', continent: '아프리카' },
  { code: 'sr', name: '수리남', capital: '파라마리보', continent: '남아메리카' },
  { code: 'lk', name: '스리랑카', capital: '스리자야와르데네푸라코테', continent: '아시아' },
  { code: 'se', name: '스웨덴', capital: '스톡홀름', continent: '유럽', easy: true },
  { code: 'ch', name: '스위스', capital: '베른', continent: '유럽', easy: true },
  { code: 'es', name: '스페인', capital: '마드리드', continent: '유럽', easy: true },
  { code: 'sk', name: '슬로바키아', capital: '브라티슬라바', continent: '유럽' },
  { code: 'si', name: '슬로베니아', capital: '류블랴나', continent: '유럽' },
  { code: 'sy', name: '시리아', capital: '다마스쿠스', continent: '아시아' },
  { code: 'sl', name: '시에라리온', capital: '프리타운', continent: '아프리카' },
  { code: 'sg', name: '싱가포르', capital: null, continent: '아시아', easy: true },
  { code: 'ae', name: '아랍에미리트', capital: '아부다비', continent: '아시아', easy: true },
  { code: 'am', name: '아르메니아', capital: '예레반', continent: '아시아' },
  {
    code: 'ar',
    name: '아르헨티나',
    capital: '부에노스아이레스',
    continent: '남아메리카',
    easy: true,
  },
  { code: 'is', name: '아이슬란드', capital: '레이캬비크', continent: '유럽' },
  { code: 'ht', name: '아이티', capital: '포르토프랭스', continent: '북아메리카' },
  { code: 'ie', name: '아일랜드', capital: '더블린', continent: '유럽', easy: true },
  { code: 'az', name: '아제르바이잔', capital: '바쿠', continent: '아시아' },
  { code: 'af', name: '아프가니스탄', capital: '카불', continent: '아시아' },
  { code: 'ad', name: '안도라', capital: null, continent: '유럽' },
  { code: 'al', name: '알바니아', capital: '티라나', continent: '유럽' },
  { code: 'dz', name: '알제리', capital: null, continent: '아프리카' },
  { code: 'ao', name: '앙골라', capital: '루안다', continent: '아프리카' },
  { code: 'ag', name: '앤티가 바부다', capital: '세인트존스', continent: '북아메리카' },
  { code: 'er', name: '에리트레아', capital: '아스마라', continent: '아프리카' },
  { code: 'sz', name: '에스와티니', capital: '음바바네', continent: '아프리카' },
  { code: 'ee', name: '에스토니아', capital: '탈린', continent: '유럽' },
  { code: 'ec', name: '에콰도르', capital: '키토', continent: '남아메리카' },
  { code: 'et', name: '에티오피아', capital: '아디스아바바', continent: '아프리카', easy: true },
  { code: 'sv', name: '엘살바도르', capital: '산살바도르', continent: '북아메리카' },
  { code: 'gb', name: '영국', capital: '런던', continent: '유럽', easy: true },
  { code: 'ye', name: '예멘', capital: '사나', continent: '아시아' },
  { code: 'om', name: '오만', capital: '무스카트', continent: '아시아' },
  { code: 'au', name: '오스트레일리아', capital: '캔버라', continent: '오세아니아', easy: true },
  { code: 'at', name: '오스트리아', capital: '빈', continent: '유럽', easy: true },
  { code: 'hn', name: '온두라스', capital: '테구시갈파', continent: '북아메리카' },
  { code: 'jo', name: '요르단', capital: '암만', continent: '아시아' },
  { code: 'ug', name: '우간다', capital: '캄팔라', continent: '아프리카' },
  { code: 'uy', name: '우루과이', capital: '몬테비데오', continent: '남아메리카', easy: true },
  { code: 'uz', name: '우즈베키스탄', capital: '타슈켄트', continent: '아시아' },
  { code: 'ua', name: '우크라이나', capital: '키이우', continent: '유럽', easy: true },
  { code: 'iq', name: '이라크', capital: '바그다드', continent: '아시아' },
  { code: 'ir', name: '이란', capital: '테헤란', continent: '아시아', easy: true },
  { code: 'il', name: '이스라엘', capital: null, continent: '아시아', easy: true },
  { code: 'eg', name: '이집트', capital: '카이로', continent: '아프리카', easy: true },
  { code: 'it', name: '이탈리아', capital: '로마', continent: '유럽', easy: true },
  { code: 'in', name: '인도', capital: '뉴델리', continent: '아시아', easy: true },
  { code: 'id', name: '인도네시아', capital: '자카르타', continent: '아시아', easy: true },
  { code: 'jp', name: '일본', capital: '도쿄', continent: '아시아', easy: true },
  { code: 'jm', name: '자메이카', capital: '킹스턴', continent: '북아메리카', easy: true },
  { code: 'zm', name: '잠비아', capital: '루사카', continent: '아프리카' },
  { code: 'gq', name: '적도 기니', capital: null, continent: '아프리카' },
  { code: 'ge', name: '조지아', capital: '트빌리시', continent: '유럽' },
  { code: 'cn', name: '중국', capital: '베이징', continent: '아시아', easy: true },
  { code: 'cf', name: '중앙아프리카 공화국', capital: '방기', continent: '아프리카' },
  { code: 'dj', name: '지부티', capital: null, continent: '아프리카' },
  { code: 'zw', name: '짐바브웨', capital: '하라레', continent: '아프리카' },
  { code: 'td', name: '차드', capital: '은자메나', continent: '아프리카' },
  { code: 'cz', name: '체코', capital: '프라하', continent: '유럽', easy: true },
  { code: 'cl', name: '칠레', capital: '산티아고', continent: '남아메리카', easy: true },
  { code: 'cm', name: '카메룬', capital: '야운데', continent: '아프리카' },
  { code: 'cv', name: '카보베르데', capital: '프라이아', continent: '아프리카' },
  { code: 'kz', name: '카자흐스탄', capital: '아스타나', continent: '아시아' },
  { code: 'qa', name: '카타르', capital: '도하', continent: '아시아', easy: true },
  { code: 'kh', name: '캄보디아', capital: '프놈펜', continent: '아시아' },
  { code: 'ca', name: '캐나다', capital: '오타와', continent: '북아메리카', easy: true },
  { code: 'ke', name: '케냐', capital: '나이로비', continent: '아프리카', easy: true },
  { code: 'km', name: '코모로', capital: '모로니', continent: '아프리카' },
  { code: 'cr', name: '코스타리카', capital: '산호세', continent: '북아메리카' },
  { code: 'ci', name: '코트디부아르', capital: '야무수크로', continent: '아프리카' },
  { code: 'co', name: '콜롬비아', capital: '보고타', continent: '남아메리카', easy: true },
  { code: 'cg', name: '콩고 공화국', capital: '브라자빌', continent: '아프리카' },
  { code: 'cd', name: '콩고 민주 공화국', capital: '킨샤사', continent: '아프리카' },
  { code: 'cu', name: '쿠바', capital: '아바나', continent: '북아메리카', easy: true },
  { code: 'kw', name: '쿠웨이트', capital: null, continent: '아시아' },
  { code: 'hr', name: '크로아티아', capital: '자그레브', continent: '유럽', easy: true },
  { code: 'kg', name: '키르기스스탄', capital: '비슈케크', continent: '아시아' },
  { code: 'ki', name: '키리바시', capital: '사우스타라와', continent: '오세아니아' },
  { code: 'cy', name: '키프로스', capital: '니코시아', continent: '유럽' },
  { code: 'tj', name: '타지키스탄', capital: '두샨베', continent: '아시아' },
  { code: 'tz', name: '탄자니아', capital: '도도마', continent: '아프리카' },
  { code: 'th', name: '태국', capital: '방콕', continent: '아시아', easy: true },
  { code: 'tg', name: '토고', capital: '로메', continent: '아프리카' },
  { code: 'to', name: '통가', capital: '누쿠알로파', continent: '오세아니아' },
  { code: 'tm', name: '투르크메니스탄', capital: '아시가바트', continent: '아시아' },
  { code: 'tv', name: '투발루', capital: '푸나푸티', continent: '오세아니아' },
  { code: 'tn', name: '튀니지', capital: '튀니스', continent: '아프리카' },
  { code: 'tr', name: '튀르키예', capital: '앙카라', continent: '아시아', easy: true },
  { code: 'tt', name: '트리니다드 토바고', capital: '포트오브스페인', continent: '북아메리카' },
  { code: 'pa', name: '파나마', capital: null, continent: '북아메리카' },
  { code: 'py', name: '파라과이', capital: '아순시온', continent: '남아메리카' },
  { code: 'pk', name: '파키스탄', capital: '이슬라마바드', continent: '아시아' },
  { code: 'pg', name: '파푸아뉴기니', capital: '포트모르즈비', continent: '오세아니아' },
  { code: 'pw', name: '팔라우', capital: '응게룰무드', continent: '오세아니아' },
  { code: 'ps', name: '팔레스타인', capital: null, continent: '아시아' },
  { code: 'pe', name: '페루', capital: '리마', continent: '남아메리카', easy: true },
  { code: 'pt', name: '포르투갈', capital: '리스본', continent: '유럽', easy: true },
  { code: 'pl', name: '폴란드', capital: '바르샤바', continent: '유럽', easy: true },
  { code: 'fr', name: '프랑스', capital: '파리', continent: '유럽', easy: true },
  { code: 'fj', name: '피지', capital: '수바', continent: '오세아니아' },
  { code: 'fi', name: '핀란드', capital: '헬싱키', continent: '유럽', easy: true },
  { code: 'ph', name: '필리핀', capital: '마닐라', continent: '아시아', easy: true },
  { code: 'hu', name: '헝가리', capital: '부다페스트', continent: '유럽', easy: true },
];
