-- 초성 퀴즈 시드 데이터 (직접 만든 문제 257개 — 음식 26·동물 28·과일·채소 25·물건 25·탈것 22·장소 25·직업 26·스포츠 26·사자성어 27·속담 27)
-- ※ 이 파일은 seeds/scripts/chosung-quiz.mjs 로 생성한다. 직접 고치지 말고 스크립트를 수정한 뒤 다시 실행할 것.
-- 여러 번 실행해도 결과가 같도록 이 게임의 문제만 지우고 다시 넣는다. (점수 기록은 유지)
-- 적용: pnpm db:seed:local (seeds/*.sql 전체가 파일명 순서대로 적용됨)

INSERT OR IGNORE INTO game (id, name, category) VALUES ('chosung-quiz', '초성 퀴즈', 'quiz');

DELETE FROM quiz_item WHERE game_id = 'chosung-quiz';

INSERT INTO quiz_item (game_id, question, answer, meta) VALUES
  ('chosung-quiz', 'ㄸㅂㅇ', '떡볶이', '{"category":"음식","hint":"빨간 양념에 떡을 볶은 분식"}'),
  ('chosung-quiz', 'ㄱㅂ', '김밥', '{"category":"음식","hint":"소풍 도시락 단골 메뉴"}'),
  ('chosung-quiz', 'ㅎㅂㄱ', '햄버거', '{"category":"음식","hint":"빵 사이에 고기 패티"}'),
  ('chosung-quiz', 'ㅂㅂㅂ', '비빔밥', '{"category":"음식","hint":"나물과 고추장을 넣고 쓱쓱 섞어 먹는 밥"}'),
  ('chosung-quiz', 'ㅂㄱㄱ', '불고기', '{"category":"음식","hint":"달콤한 간장 양념에 재운 소고기 구이"}'),
  ('chosung-quiz', 'ㅅㄱㅅ', '삼겹살', '{"category":"음식","hint":"불판에 지글지글 구워 먹는 돼지고기 부위"}'),
  ('chosung-quiz', 'ㄷㅈㅉㄱ', '된장찌개', '{"category":"음식","hint":"구수한 장을 풀어 끓인 찌개"}'),
  ('chosung-quiz', 'ㄱㅊㅉㄱ', '김치찌개', '{"category":"음식","hint":"신 김치와 돼지고기로 끓인 찌개"}'),
  ('chosung-quiz', 'ㅉㅈㅁ', '짜장면', '{"category":"음식","hint":"중국집의 까만 소스 면 요리","aliases":["자장면"]}'),
  ('chosung-quiz', 'ㅉㅃ', '짬뽕', '{"category":"음식","hint":"중국집의 빨간 국물 면 요리"}'),
  ('chosung-quiz', 'ㄴㅁ', '냉면', '{"category":"음식","hint":"여름에 먹는 차가운 면 요리"}'),
  ('chosung-quiz', 'ㄹㅁ', '라면', '{"category":"음식","hint":"꼬불꼬불 면을 끓여 먹는 인스턴트 음식"}'),
  ('chosung-quiz', 'ㅅㄷ', '순대', '{"category":"음식","hint":"당면을 채운 분식, 떡볶이 국물에 찍어 먹기도"}'),
  ('chosung-quiz', 'ㅁㄷ', '만두', '{"category":"음식","hint":"밀가루 피 속에 소를 채워 빚은 음식"}'),
  ('chosung-quiz', 'ㅊㅋ', '치킨', '{"category":"음식","hint":"닭을 튀긴 야식 단골 메뉴"}'),
  ('chosung-quiz', 'ㄷㄱㅅ', '돈가스', '{"category":"음식","hint":"돼지고기에 빵가루를 입혀 튀긴 요리","aliases":["돈까스"]}'),
  ('chosung-quiz', 'ㅈㅊ', '잡채', '{"category":"음식","hint":"당면과 채소를 볶은 잔치 음식"}'),
  ('chosung-quiz', 'ㅅㄱㅌ', '삼계탕', '{"category":"음식","hint":"복날 먹는 닭 한 마리 보양식"}'),
  ('chosung-quiz', 'ㄸㄱ', '떡국', '{"category":"음식","hint":"설날에 먹으면 한 살 더 먹는다"}'),
  ('chosung-quiz', 'ㅂㅇㅃ', '붕어빵', '{"category":"음식","hint":"물고기 모양 틀에 구운 겨울 간식"}'),
  ('chosung-quiz', 'ㅎㄸ', '호떡', '{"category":"음식","hint":"설탕 시럽이 든 납작한 겨울 길거리 간식"}'),
  ('chosung-quiz', 'ㅍㅂㅅ', '팥빙수', '{"category":"음식","hint":"얼음 위에 단팥을 올린 여름 디저트"}'),
  ('chosung-quiz', 'ㅂㄷㅉㄱ', '부대찌개', '{"category":"음식","hint":"햄과 소시지를 듬뿍 넣은 찌개"}'),
  ('chosung-quiz', 'ㅊㅂ', '초밥', '{"category":"음식","hint":"밥 위에 생선 회를 올린 일본 음식"}'),
  ('chosung-quiz', 'ㅋㄹ', '카레', '{"category":"음식","hint":"노란 소스를 밥에 얹어 먹는 음식"}'),
  ('chosung-quiz', 'ㄱㅈㅌ', '감자탕', '{"category":"음식","hint":"돼지 등뼈와 감자로 끓인 탕"}'),
  ('chosung-quiz', 'ㅎㄹㅇ', '호랑이', '{"category":"동물","hint":"줄무늬가 있는 맹수"}'),
  ('chosung-quiz', 'ㅋㄲㄹ', '코끼리', '{"category":"동물","hint":"코가 아주 긴 동물"}'),
  ('chosung-quiz', 'ㅍㄱ', '펭귄', '{"category":"동물","hint":"남극에 사는 날지 못하는 새"}'),
  ('chosung-quiz', 'ㄱㅇㅇ', '고양이', '{"category":"동물","hint":"야옹 하고 우는 반려동물"}'),
  ('chosung-quiz', 'ㄱㅇㅈ', '강아지', '{"category":"동물","hint":"멍멍 짖는 어린 개"}'),
  ('chosung-quiz', 'ㄱㄹ', '기린', '{"category":"동물","hint":"목이 가장 긴 동물"}'),
  ('chosung-quiz', 'ㅅㅈ', '사자', '{"category":"동물","hint":"갈기가 멋진 초원의 왕"}'),
  ('chosung-quiz', 'ㅇㅅㅇ', '원숭이', '{"category":"동물","hint":"바나나를 좋아하는 나무 타기 선수"}'),
  ('chosung-quiz', 'ㄷㄹㅈ', '다람쥐', '{"category":"동물","hint":"도토리를 볼에 가득 넣는 작은 동물"}'),
  ('chosung-quiz', 'ㄱㅂㅇ', '거북이', '{"category":"동물","hint":"등딱지가 있는 느림보"}'),
  ('chosung-quiz', 'ㅌㄲ', '토끼', '{"category":"동물","hint":"귀가 길고 깡충깡충 뛴다"}'),
  ('chosung-quiz', 'ㅎㅁ', '하마', '{"category":"동물","hint":"입이 아주 큰 물가의 거구"}'),
  ('chosung-quiz', 'ㅇㅇ', '악어', '{"category":"동물","hint":"강가에 숨어 있는 비늘 덮인 파충류"}'),
  ('chosung-quiz', 'ㄷㅅㄹ', '독수리', '{"category":"동물","hint":"날카로운 발톱을 가진 하늘의 사냥꾼"}'),
  ('chosung-quiz', 'ㅇㅁㅅ', '앵무새', '{"category":"동물","hint":"사람 말을 따라 하는 새"}'),
  ('chosung-quiz', 'ㄱㅅㄷㅊ', '고슴도치', '{"category":"동물","hint":"등에 가시가 가득한 작은 동물"}'),
  ('chosung-quiz', 'ㅋㄱㄹ', '캥거루', '{"category":"동물","hint":"배 주머니에 새끼를 넣고 다니는 호주 동물"}'),
  ('chosung-quiz', 'ㄴㄱㄹ', '너구리', '{"category":"동물","hint":"눈가에 검은 무늬가 있는 갯과 동물"}'),
  ('chosung-quiz', 'ㄷㄱㄹ', '돌고래', '{"category":"동물","hint":"초음파로 대화하는 똑똑한 바다 포유류"}'),
  ('chosung-quiz', 'ㅅㅇ', '상어', '{"category":"동물","hint":"지느러미를 물 위로 내밀고 다니는 바다의 포식자"}'),
  ('chosung-quiz', 'ㅁㅇ', '문어', '{"category":"동물","hint":"다리가 여덟 개, 먹물을 뿜는다"}'),
  ('chosung-quiz', 'ㅇㅈㅇ', '오징어', '{"category":"동물","hint":"다리가 열 개, 말리면 술안주"}'),
  ('chosung-quiz', 'ㅂㅇㅇ', '부엉이', '{"category":"동물","hint":"밤에 깨어 있는, 머리에 깃털 귀가 있는 새"}'),
  ('chosung-quiz', 'ㅇㄹㅁ', '얼룩말', '{"category":"동물","hint":"흑백 줄무늬의 초원 동물"}'),
  ('chosung-quiz', 'ㅍㄷ', '판다', '{"category":"동물","hint":"대나무를 먹는 흑백 곰"}'),
  ('chosung-quiz', 'ㄴㅌ', '낙타', '{"category":"동물","hint":"등에 혹이 있는 사막의 동물"}'),
  ('chosung-quiz', 'ㄷㄷㅈ', '두더지', '{"category":"동물","hint":"땅굴을 파는 동물, 게임에서는 망치로 맞는다"}'),
  ('chosung-quiz', 'ㄱㄱㄹ', '개구리', '{"category":"동물","hint":"올챙이가 자라서 된다"}'),
  ('chosung-quiz', 'ㅅㄱ', '사과', '{"category":"과일·채소","hint":"빨갛고 아삭한 과일"}'),
  ('chosung-quiz', 'ㅂㄴㄴ', '바나나', '{"category":"과일·채소","hint":"노랗고 길쭉한 과일"}'),
  ('chosung-quiz', 'ㅅㅂ', '수박', '{"category":"과일·채소","hint":"여름에 먹는 커다란 줄무늬 과일"}'),
  ('chosung-quiz', 'ㄸㄱ', '딸기', '{"category":"과일·채소","hint":"겉에 씨가 콕콕 박힌 빨간 과일"}'),
  ('chosung-quiz', 'ㅍㄷ', '포도', '{"category":"과일·채소","hint":"송이송이 달린 보라색 과일"}'),
  ('chosung-quiz', 'ㅂㅅㅇ', '복숭아', '{"category":"과일·채소","hint":"털이 보송한 분홍빛 여름 과일"}'),
  ('chosung-quiz', 'ㄱ', '귤', '{"category":"과일·채소","hint":"겨울에 손이 노래지도록 까먹는 과일"}'),
  ('chosung-quiz', 'ㅍㅇㅇㅍ', '파인애플', '{"category":"과일·채소","hint":"왕관 같은 잎이 달린 열대 과일"}'),
  ('chosung-quiz', 'ㅊㅇ', '참외', '{"category":"과일·채소","hint":"노란 껍질에 하얀 줄무늬가 있는 여름 과일"}'),
  ('chosung-quiz', 'ㄹㅁ', '레몬', '{"category":"과일·채소","hint":"아주 신 노란 과일"}'),
  ('chosung-quiz', 'ㅊㄹ', '체리', '{"category":"과일·채소","hint":"꼭지가 길게 달린 작고 빨간 과일"}'),
  ('chosung-quiz', 'ㅋㅇ', '키위', '{"category":"과일·채소","hint":"갈색 털 껍질 속 초록 과일"}'),
  ('chosung-quiz', 'ㅁㄱ', '망고', '{"category":"과일·채소","hint":"노란 과육의 달콤한 열대 과일"}'),
  ('chosung-quiz', 'ㄷㄱ', '당근', '{"category":"과일·채소","hint":"토끼가 좋아하는 주황색 채소"}'),
  ('chosung-quiz', 'ㄱㅈ', '감자', '{"category":"과일·채소","hint":"땅속에서 캐는 동글동글한 덩이줄기, 튀기면 프라이"}'),
  ('chosung-quiz', 'ㄱㄱㅁ', '고구마', '{"category":"과일·채소","hint":"겨울에 구워 먹는 달콤한 덩이뿌리"}'),
  ('chosung-quiz', 'ㅇㅍ', '양파', '{"category":"과일·채소","hint":"썰면 눈물이 나는 채소"}'),
  ('chosung-quiz', 'ㅇㅇ', '오이', '{"category":"과일·채소","hint":"길쭉한 초록 채소, 피클의 재료"}'),
  ('chosung-quiz', 'ㅌㅁㅌ', '토마토', '{"category":"과일·채소","hint":"과일일까 채소일까? 빨갛고 동그란 열매"}'),
  ('chosung-quiz', 'ㅂㄹㅋㄹ', '브로콜리', '{"category":"과일·채소","hint":"작은 나무처럼 생긴 초록 채소"}'),
  ('chosung-quiz', 'ㅇㅅㅅ', '옥수수', '{"category":"과일·채소","hint":"노란 알갱이가 줄지어 박힌 곡물"}'),
  ('chosung-quiz', 'ㅅㄱㅊ', '시금치', '{"category":"과일·채소","hint":"나물로 무쳐 먹는 초록 잎채소"}'),
  ('chosung-quiz', 'ㄱㅊ', '고추', '{"category":"과일·채소","hint":"맵고 길쭉한 빨강·초록 채소"}'),
  ('chosung-quiz', 'ㅁㄴ', '마늘', '{"category":"과일·채소","hint":"한국 요리에 빠지지 않는 매운 알뿌리"}'),
  ('chosung-quiz', 'ㅎㅂ', '호박', '{"category":"과일·채소","hint":"핼러윈 등불을 만드는 둥근 채소"}'),
  ('chosung-quiz', 'ㄴㅈㄱ', '냉장고', '{"category":"물건","hint":"음식을 차갑게 보관하는 가전"}'),
  ('chosung-quiz', 'ㅅㅌㄱ', '세탁기', '{"category":"물건","hint":"빨래를 해주는 기계"}'),
  ('chosung-quiz', 'ㅇㅅ', '우산', '{"category":"물건","hint":"비 오는 날 펼쳐 쓴다"}'),
  ('chosung-quiz', 'ㅇㅍ', '연필', '{"category":"물건","hint":"깎아서 쓰는 필기구"}'),
  ('chosung-quiz', 'ㅈㅇㄱ', '지우개', '{"category":"물건","hint":"연필 글씨를 지우는 문구"}'),
  ('chosung-quiz', 'ㄱㅇ', '가위', '{"category":"물건","hint":"종이를 자르는 도구, 바위·보와 함께"}'),
  ('chosung-quiz', 'ㅇㄱ', '안경', '{"category":"물건","hint":"눈이 나쁠 때 코 위에 걸치는 것"}'),
  ('chosung-quiz', 'ㄱㅇ', '거울', '{"category":"물건","hint":"내 모습을 비춰 보는 물건"}'),
  ('chosung-quiz', 'ㅊㅅ', '칫솔', '{"category":"물건","hint":"이를 닦는 솔"}'),
  ('chosung-quiz', 'ㅂㄱ', '베개', '{"category":"물건","hint":"잘 때 머리를 받치는 것"}'),
  ('chosung-quiz', 'ㅇㅂ', '이불', '{"category":"물건","hint":"잘 때 덮는 것"}'),
  ('chosung-quiz', 'ㅅㄱㄹ', '숟가락', '{"category":"물건","hint":"밥과 국을 떠먹는 도구","aliases":["숫가락"]}'),
  ('chosung-quiz', 'ㅈㄱㄹ', '젓가락', '{"category":"물건","hint":"두 짝으로 반찬을 집는 도구","aliases":["젖가락"]}'),
  ('chosung-quiz', 'ㅅㅍㄱ', '선풍기', '{"category":"물건","hint":"날개가 돌아가며 바람을 만드는 여름 가전"}'),
  ('chosung-quiz', 'ㅇㅇㅋ', '에어컨', '{"category":"물건","hint":"찬바람을 내뿜는 냉방 기계"}'),
  ('chosung-quiz', 'ㅈㅈㄹㅇㅈ', '전자레인지', '{"category":"물건","hint":"음식을 빙글빙글 돌리며 데우는 가전"}'),
  ('chosung-quiz', 'ㅎㄷㅍ', '휴대폰', '{"category":"물건","hint":"들고 다니는 전화기"}'),
  ('chosung-quiz', 'ㅇㅅ', '열쇠', '{"category":"물건","hint":"자물쇠를 여는 것"}'),
  ('chosung-quiz', 'ㅈㄱ', '지갑', '{"category":"물건","hint":"돈과 카드를 넣고 다니는 것"}'),
  ('chosung-quiz', 'ㅊㅅㄱ', '청소기', '{"category":"물건","hint":"먼지를 빨아들이는 가전"}'),
  ('chosung-quiz', 'ㅇㄷㅎ', '운동화', '{"category":"물건","hint":"달리기할 때 신는 신발"}'),
  ('chosung-quiz', 'ㅈㄱ', '장갑', '{"category":"물건","hint":"겨울에 손을 따뜻하게 감싸는 것"}'),
  ('chosung-quiz', 'ㄹㅁㅋ', '리모컨', '{"category":"물건","hint":"소파에 앉아 TV 채널을 바꾸는 것","aliases":["리모콘"]}'),
  ('chosung-quiz', 'ㄷㄹ', '달력', '{"category":"물건","hint":"한 장씩 넘기며 날짜를 보는 것"}'),
  ('chosung-quiz', 'ㅇㅁ', '양말', '{"category":"물건","hint":"신발 신기 전에 발에 신는 것"}'),
  ('chosung-quiz', 'ㅂㅎㄱ', '비행기', '{"category":"탈것","hint":"하늘을 나는 교통수단"}'),
  ('chosung-quiz', 'ㅈㅈㄱ', '자전거', '{"category":"탈것","hint":"두 바퀴로 페달을 밟는다"}'),
  ('chosung-quiz', 'ㅈㅎㅊ', '지하철', '{"category":"탈것","hint":"땅 밑으로 다니는 열차"}'),
  ('chosung-quiz', 'ㅂㅅ', '버스', '{"category":"탈것","hint":"정류장에서 기다렸다 타는 대중교통"}'),
  ('chosung-quiz', 'ㅌㅅ', '택시', '{"category":"탈것","hint":"손을 흔들어 세우고 미터기로 요금을 낸다"}'),
  ('chosung-quiz', 'ㄱㅊ', '기차', '{"category":"탈것","hint":"철로 위를 칙칙폭폭 달린다"}'),
  ('chosung-quiz', 'ㅇㅌㅂㅇ', '오토바이', '{"category":"탈것","hint":"헬멧 쓰고 타는 두 바퀴 엔진 탈것"}'),
  ('chosung-quiz', 'ㅎㄹㅋㅌ', '헬리콥터', '{"category":"탈것","hint":"머리 위 프로펠러로 떠오르는 탈것"}'),
  ('chosung-quiz', 'ㅈㅅㅎ', '잠수함', '{"category":"탈것","hint":"바닷속으로 다니는 배"}'),
  ('chosung-quiz', 'ㄱㄱㅊ', '구급차', '{"category":"탈것","hint":"삐뽀삐뽀, 환자를 병원으로"}'),
  ('chosung-quiz', 'ㅅㅂㅊ', '소방차', '{"category":"탈것","hint":"불을 끄러 출동하는 빨간 차"}'),
  ('chosung-quiz', 'ㄱㅊㅊ', '경찰차', '{"category":"탈것","hint":"경광등을 번쩍이며 범인을 쫓는 차"}'),
  ('chosung-quiz', 'ㅌㄹ', '트럭', '{"category":"탈것","hint":"짐칸에 화물을 싣는 차"}'),
  ('chosung-quiz', 'ㅇㅁㅊ', '유모차', '{"category":"탈것","hint":"아기를 태우고 밀고 다니는 것"}'),
  ('chosung-quiz', 'ㅋㅂㄷ', '킥보드', '{"category":"탈것","hint":"한 발로 땅을 차며 타는 것"}'),
  ('chosung-quiz', 'ㅇㄱㄱ', '열기구', '{"category":"탈것","hint":"뜨거운 공기로 떠오르는 커다란 풍선"}'),
  ('chosung-quiz', 'ㄹㅋ', '로켓', '{"category":"탈것","hint":"우주로 쏘아 올리는 탈것"}'),
  ('chosung-quiz', 'ㅋㅇㅂㅋ', '케이블카', '{"category":"탈것","hint":"줄에 매달려 산을 오르는 탈것"}'),
  ('chosung-quiz', 'ㅇㅌ', '요트', '{"category":"탈것","hint":"돛을 달고 바다를 누비는 배"}'),
  ('chosung-quiz', 'ㅆㅁ', '썰매', '{"category":"탈것","hint":"눈 위를 미끄러지는 탈것, 산타 할아버지도 탄다"}'),
  ('chosung-quiz', 'ㅁㅊ', '마차', '{"category":"탈것","hint":"말이 끄는 수레"}'),
  ('chosung-quiz', 'ㅋㅍㅋ', '캠핑카', '{"category":"탈것","hint":"집처럼 자고 먹을 수 있는 차"}'),
  ('chosung-quiz', 'ㄷㅅㄱ', '도서관', '{"category":"장소","hint":"책을 빌려 볼 수 있는 곳"}'),
  ('chosung-quiz', 'ㅂㅇ', '병원', '{"category":"장소","hint":"아플 때 의사 선생님을 만나는 곳"}'),
  ('chosung-quiz', 'ㅎㄱ', '학교', '{"category":"장소","hint":"선생님과 친구들이 있는, 아침마다 가는 곳"}'),
  ('chosung-quiz', 'ㄴㅇㄱㅇ', '놀이공원', '{"category":"장소","hint":"롤러코스터와 회전목마가 있는 곳"}'),
  ('chosung-quiz', 'ㄷㅁㅇ', '동물원', '{"category":"장소","hint":"여러 동물을 구경하는 곳"}'),
  ('chosung-quiz', 'ㅅㅇㅈ', '수영장', '{"category":"장소","hint":"물안경 쓰고 헤엄치는 곳"}'),
  ('chosung-quiz', 'ㄱㅊㅅ', '경찰서', '{"category":"장소","hint":"도둑을 잡으면 데려가는 곳"}'),
  ('chosung-quiz', 'ㅅㅂㅅ', '소방서', '{"category":"장소","hint":"불자동차가 출동을 기다리는 곳"}'),
  ('chosung-quiz', 'ㅇㅊㄱ', '우체국', '{"category":"장소","hint":"편지와 택배를 부치는 곳"}'),
  ('chosung-quiz', 'ㅇㅎ', '은행', '{"category":"장소","hint":"통장을 만들고 돈을 맡기는 곳"}'),
  ('chosung-quiz', 'ㅍㅇㅈ', '편의점', '{"category":"장소","hint":"24시간 문을 여는 작은 가게"}'),
  ('chosung-quiz', 'ㅇㅎㄱ', '영화관', '{"category":"장소","hint":"팝콘 먹으며 큰 화면을 보는 곳"}'),
  ('chosung-quiz', 'ㅁㅇㅅ', '미용실', '{"category":"장소","hint":"머리를 자르고 염색하는 곳"}'),
  ('chosung-quiz', 'ㅇㄱ', '약국', '{"category":"장소","hint":"처방전을 들고 가는 곳"}'),
  ('chosung-quiz', 'ㄱㅎ', '공항', '{"category":"장소","hint":"비행기를 타러 가는 곳"}'),
  ('chosung-quiz', 'ㅂㅁㄱ', '박물관', '{"category":"장소","hint":"옛 유물을 전시하는 곳"}'),
  ('chosung-quiz', 'ㄴㅇㅌ', '놀이터', '{"category":"장소","hint":"미끄럼틀과 그네가 있는 곳"}'),
  ('chosung-quiz', 'ㅁㅇㅌ', '목욕탕', '{"category":"장소","hint":"때를 밀고 온탕에 들어가는 곳"}'),
  ('chosung-quiz', 'ㅁㅂㄱ', '문방구', '{"category":"장소","hint":"학교 앞 학용품 가게"}'),
  ('chosung-quiz', 'ㅃㅈ', '빵집', '{"category":"장소","hint":"갓 구운 냄새가 솔솔 나는 가게"}'),
  ('chosung-quiz', 'ㅈㅊㅈ', '주차장', '{"category":"장소","hint":"차를 세워 두는 곳"}'),
  ('chosung-quiz', 'ㅉㅈㅂ', '찜질방', '{"category":"장소","hint":"양머리 수건 쓰고 식혜 마시는 곳"}'),
  ('chosung-quiz', 'ㄴㄹㅂ', '노래방', '{"category":"장소","hint":"마이크 잡고 부르면 점수가 나오는 곳"}'),
  ('chosung-quiz', 'ㅅㅈ', '시장', '{"category":"장소","hint":"흥정하며 장보는 북적이는 곳"}'),
  ('chosung-quiz', 'ㅇㄷㅈ', '운동장', '{"category":"장소","hint":"체육 시간에 뛰노는 학교의 넓은 마당"}'),
  ('chosung-quiz', 'ㅅㅂㄱ', '소방관', '{"category":"직업","hint":"불을 끄고 사람을 구하는 사람"}'),
  ('chosung-quiz', 'ㄱㅊㄱ', '경찰관', '{"category":"직업","hint":"범인을 잡고 질서를 지키는 사람"}'),
  ('chosung-quiz', 'ㅇㅅ', '의사', '{"category":"직업","hint":"병을 진찰하고 치료하는 사람"}'),
  ('chosung-quiz', 'ㄱㅎㅅ', '간호사', '{"category":"직업","hint":"병원에서 환자를 돌보고 주사를 놓는 사람"}'),
  ('chosung-quiz', 'ㅅㅅㄴ', '선생님', '{"category":"직업","hint":"학교에서 학생을 가르치는 사람"}'),
  ('chosung-quiz', 'ㅇㄹㅅ', '요리사', '{"category":"직업","hint":"주방에서 음식을 만드는 사람"}'),
  ('chosung-quiz', 'ㄱㅅ', '가수', '{"category":"직업","hint":"무대에서 노래하는 사람"}'),
  ('chosung-quiz', 'ㅂㅇ', '배우', '{"category":"직업","hint":"드라마와 영화에서 연기하는 사람"}'),
  ('chosung-quiz', 'ㅎㄱ', '화가', '{"category":"직업","hint":"그림을 그리는 사람"}'),
  ('chosung-quiz', 'ㅇㅈㅂㅎㅅ', '우주비행사', '{"category":"직업","hint":"우주선을 타고 우주로 가는 사람"}'),
  ('chosung-quiz', 'ㄱㅎㅈ', '과학자', '{"category":"직업","hint":"실험하고 연구하는 사람"}'),
  ('chosung-quiz', 'ㅂㅎㅅ', '변호사', '{"category":"직업","hint":"법정에서 의뢰인을 지켜 주는 사람"}'),
  ('chosung-quiz', 'ㅍㅅ', '판사', '{"category":"직업","hint":"법정에서 판결을 내리는 사람"}'),
  ('chosung-quiz', 'ㄱㅈ', '기자', '{"category":"직업","hint":"취재해서 뉴스를 쓰는 사람"}'),
  ('chosung-quiz', 'ㄴㅂ', '농부', '{"category":"직업","hint":"논밭에서 곡식을 기르는 사람"}'),
  ('chosung-quiz', 'ㅇㅂ', '어부', '{"category":"직업","hint":"바다에서 물고기를 잡는 사람"}'),
  ('chosung-quiz', 'ㅈㅃㅅ', '제빵사', '{"category":"직업","hint":"빵을 굽는 사람"}'),
  ('chosung-quiz', 'ㅁㅇㅅ', '미용사', '{"category":"직업","hint":"머리를 잘라 주는 사람"}'),
  ('chosung-quiz', 'ㅈㅈㅅ', '조종사', '{"category":"직업","hint":"비행기를 모는 사람"}'),
  ('chosung-quiz', 'ㅅㅇㅅ', '수의사', '{"category":"직업","hint":"아픈 동물을 치료하는 사람"}'),
  ('chosung-quiz', 'ㅁㅅㅅ', '마술사', '{"category":"직업","hint":"모자에서 비둘기를 꺼내는 사람"}'),
  ('chosung-quiz', 'ㅇㄴㅇㅅ', '아나운서', '{"category":"직업","hint":"방송에서 뉴스를 읽는 사람"}'),
  ('chosung-quiz', 'ㄱㅊㄱ', '건축가', '{"category":"직업","hint":"건물을 설계하는 사람"}'),
  ('chosung-quiz', 'ㅇㅅ', '약사', '{"category":"직업","hint":"처방전대로 약을 지어 주는 사람"}'),
  ('chosung-quiz', 'ㅈㅂㅇ', '집배원', '{"category":"직업","hint":"편지를 배달하는 사람"}'),
  ('chosung-quiz', 'ㅍㄹㄱㄹㅁ', '프로그래머', '{"category":"직업","hint":"코드를 짜서 프로그램을 만드는 사람"}'),
  ('chosung-quiz', 'ㄴㄱ', '농구', '{"category":"스포츠","hint":"공을 링에 넣는 경기"}'),
  ('chosung-quiz', 'ㅅㅇ', '수영', '{"category":"스포츠","hint":"물에서 하는 운동"}'),
  ('chosung-quiz', 'ㅊㄱ', '축구', '{"category":"스포츠","hint":"손을 쓰지 않고 공을 차서 골을 넣는 경기"}'),
  ('chosung-quiz', 'ㅇㄱ', '야구', '{"category":"스포츠","hint":"투수가 던지고 타자가 치는 경기"}'),
  ('chosung-quiz', 'ㅂㄱ', '배구', '{"category":"스포츠","hint":"네트 너머로 공을 때려 넘기는 경기"}'),
  ('chosung-quiz', 'ㅌㄱ', '탁구', '{"category":"스포츠","hint":"탁자 위에서 작은 공을 주고받는 경기"}'),
  ('chosung-quiz', 'ㅌㄴㅅ', '테니스', '{"category":"스포츠","hint":"라켓으로 노란 공을 치는 코트 경기"}'),
  ('chosung-quiz', 'ㄱㅍ', '골프', '{"category":"스포츠","hint":"작은 공을 홀컵에 넣는 18홀 경기"}'),
  ('chosung-quiz', 'ㅂㄹ', '볼링', '{"category":"스포츠","hint":"공을 굴려 핀 10개를 쓰러뜨린다"}'),
  ('chosung-quiz', 'ㅇㄱ', '양궁', '{"category":"스포츠","hint":"활을 쏴 과녁 정중앙을 노린다"}'),
  ('chosung-quiz', 'ㅌㄱㄷ', '태권도', '{"category":"스포츠","hint":"한국에서 시작된 발차기 무술"}'),
  ('chosung-quiz', 'ㅆㄹ', '씨름', '{"category":"스포츠","hint":"모래판에서 샅바를 잡고 겨룬다"}'),
  ('chosung-quiz', 'ㅍㅅ', '펜싱', '{"category":"스포츠","hint":"마스크를 쓰고 칼로 찌르는 경기"}'),
  ('chosung-quiz', 'ㅅㅋ', '스키', '{"category":"스포츠","hint":"눈 덮인 슬로프를 판 두 개로 내려온다"}'),
  ('chosung-quiz', 'ㅁㄹㅌ', '마라톤', '{"category":"스포츠","hint":"42.195km를 달리는 경기"}'),
  ('chosung-quiz', 'ㅂㄷㅁㅌ', '배드민턴', '{"category":"스포츠","hint":"깃털 달린 공을 라켓으로 치는 경기"}'),
  ('chosung-quiz', 'ㄷㄱ', '당구', '{"category":"스포츠","hint":"큐로 공을 쳐서 맞히는 경기"}'),
  ('chosung-quiz', 'ㄱㅌ', '권투', '{"category":"스포츠","hint":"글러브를 끼고 주먹으로 겨루는 경기"}'),
  ('chosung-quiz', 'ㅋㄹ', '컬링', '{"category":"스포츠","hint":"빙판 위에서 돌을 밀고 솔질하는 경기"}'),
  ('chosung-quiz', 'ㅊㅈ', '체조', '{"category":"스포츠","hint":"철봉·평균대·마루에서 연기하는 종목"}'),
  ('chosung-quiz', 'ㅍㄱ', '피구', '{"category":"스포츠","hint":"공에 맞으면 밖으로 나가는 학교 체육 놀이"}'),
  ('chosung-quiz', 'ㅅㄱ', '사격', '{"category":"스포츠","hint":"총으로 표적을 맞히는 경기"}'),
  ('chosung-quiz', 'ㅅㅁ', '승마', '{"category":"스포츠","hint":"말을 타는 운동"}'),
  ('chosung-quiz', 'ㅈㄴㄱ', '줄넘기', '{"category":"스포츠","hint":"줄을 돌려 넘는 운동, 이단뛰기도 있다"}'),
  ('chosung-quiz', 'ㄹㅂ', '럭비', '{"category":"스포츠","hint":"타원형 공을 들고 달리는 경기"}'),
  ('chosung-quiz', 'ㅇㄷ', '유도', '{"category":"스포츠","hint":"상대를 메치고 누르는 무술"}'),
  ('chosung-quiz', 'ㅇㅅㅇㅈ', '일석이조', '{"category":"사자성어","hint":"돌 하나로 새 두 마리를 잡는다"}'),
  ('chosung-quiz', 'ㅈㅅㅅㅇ', '작심삼일', '{"category":"사자성어","hint":"굳게 먹은 마음이 사흘을 못 간다"}'),
  ('chosung-quiz', 'ㄷㅁㅅㄷ', '동문서답', '{"category":"사자성어","hint":"묻는 말에 엉뚱한 대답"}'),
  ('chosung-quiz', 'ㅇㅂㅁㅎ', '유비무환', '{"category":"사자성어","hint":"미리 준비하면 걱정이 없다"}'),
  ('chosung-quiz', 'ㅇㅇㅈㅇ', '우왕좌왕', '{"category":"사자성어","hint":"이리저리 왔다 갔다 갈피를 못 잡음"}'),
  ('chosung-quiz', 'ㅇㄹㅁㅈ', '오리무중', '{"category":"사자성어","hint":"짙은 안개 속처럼 행방을 알 수 없음"}'),
  ('chosung-quiz', 'ㄱㅅㅊㅎ', '금상첨화', '{"category":"사자성어","hint":"좋은 일에 좋은 일이 더해짐"}'),
  ('chosung-quiz', 'ㅅㅅㄱㅅ', '설상가상', '{"category":"사자성어","hint":"나쁜 일에 나쁜 일이 겹침 (눈 위에 서리)"}'),
  ('chosung-quiz', 'ㄷㄱㅁㅅ', '대기만성', '{"category":"사자성어","hint":"큰 그릇은 늦게 이루어진다"}'),
  ('chosung-quiz', 'ㅅㅈㅍㄱ', '십중팔구', '{"category":"사자성어","hint":"열에 여덟아홉, 거의 틀림없음"}'),
  ('chosung-quiz', 'ㅇㅅㅊㄹ', '일사천리', '{"category":"사자성어","hint":"일이 거침없이 빠르게 진행됨"}'),
  ('chosung-quiz', 'ㅈㅇㅈㄷ', '자업자득', '{"category":"사자성어","hint":"자기가 한 일의 결과를 자기가 받음"}'),
  ('chosung-quiz', 'ㄱㅇㅇㅅ', '감언이설', '{"category":"사자성어","hint":"달콤한 말로 남을 꾀는 것"}'),
  ('chosung-quiz', 'ㅇㅅㅈㅅ', '이심전심', '{"category":"사자성어","hint":"말하지 않아도 마음이 서로 통함"}'),
  ('chosung-quiz', 'ㅊㄱㅁㅂ', '천고마비', '{"category":"사자성어","hint":"하늘이 높고 말이 살찌는 가을"}'),
  ('chosung-quiz', 'ㅈㅁㄱㅇ', '죽마고우', '{"category":"사자성어","hint":"대나무 말을 타고 놀던 어릴 적 친구"}'),
  ('chosung-quiz', 'ㄱㅈㄱㄹ', '고진감래', '{"category":"사자성어","hint":"쓴 것이 다하면 단 것이 온다"}'),
  ('chosung-quiz', 'ㄱㅇㅂㄱ', '과유불급', '{"category":"사자성어","hint":"지나침은 모자람과 같다"}'),
  ('chosung-quiz', 'ㅇㅂㅈㄹ', '어부지리', '{"category":"사자성어","hint":"둘이 다투는 사이 제3자가 얻는 이득"}'),
  ('chosung-quiz', 'ㅊㅊㅇㄹ', '청출어람', '{"category":"사자성어","hint":"제자가 스승보다 나음"}'),
  ('chosung-quiz', 'ㅇㅈㅅㅈ', '역지사지', '{"category":"사자성어","hint":"처지를 바꿔 생각해 봄"}'),
  ('chosung-quiz', 'ㅈㅎㅇㅂ', '전화위복', '{"category":"사자성어","hint":"재앙이 바뀌어 오히려 복이 됨"}'),
  ('chosung-quiz', 'ㅇㅊㅇㅈ', '일취월장', '{"category":"사자성어","hint":"날로 달로 실력이 늚"}'),
  ('chosung-quiz', 'ㄷㄷㅇㅅ', '다다익선', '{"category":"사자성어","hint":"많으면 많을수록 좋다"}'),
  ('chosung-quiz', 'ㅇㄷㅅㅁ', '용두사미', '{"category":"사자성어","hint":"시작은 거창하나 끝은 흐지부지"}'),
  ('chosung-quiz', 'ㅅㅇㅈㅁ', '새옹지마', '{"category":"사자성어","hint":"인생의 좋고 나쁜 일은 미리 알 수 없다"}'),
  ('chosung-quiz', 'ㅁㅅㅁㅎ', '막상막하', '{"category":"사자성어","hint":"서로 비슷해서 우열을 가리기 어려움"}'),
  ('chosung-quiz', 'ㄱㄴ ㅁㅇ ㄱㅇㅇ ㅇㄴ ㅁㅇ ㄱㄷ', '가는 말이 고와야 오는 말이 곱다', '{"category":"속담","hint":"내가 남에게 잘해야 남도 나에게 잘한다"}'),
  ('chosung-quiz', 'ㄴㅁㅇ ㅅㄱ ㄷㄱ ㅂㅁㅇ ㅈㄱ ㄷㄴㄷ', '낮말은 새가 듣고 밤말은 쥐가 듣는다', '{"category":"속담","hint":"아무도 안 듣는 것 같아도 말조심"}'),
  ('chosung-quiz', 'ㄷㅈ ㅁㅇ ㅇㄷㄷ', '등잔 밑이 어둡다', '{"category":"속담","hint":"가까이 있는 것을 오히려 잘 모른다"}'),
  ('chosung-quiz', 'ㅂ ㅇㄴ ㅁㅇ ㅊ ㄹ ㄱㄷ', '발 없는 말이 천 리 간다', '{"category":"속담","hint":"말은 순식간에 멀리 퍼진다"}'),
  ('chosung-quiz', 'ㅅ ㅅ ㅂㄹ ㅇㄷㄲㅈ ㄱㄷ', '세 살 버릇 여든까지 간다', '{"category":"속담","hint":"어릴 때 버릇은 늙어서도 고치기 어렵다"}'),
  ('chosung-quiz', 'ㅅ ㅇㄱ ㅇㅇㄱ ㄱㅊㄷ', '소 잃고 외양간 고친다', '{"category":"속담","hint":"일이 터진 뒤에야 대비한다"}'),
  ('chosung-quiz', 'ㅇㅅㅇㄷ ㄴㅁㅇㅅ ㄸㅇㅈㄷ', '원숭이도 나무에서 떨어진다', '{"category":"속담","hint":"잘하는 사람도 실수할 때가 있다"}'),
  ('chosung-quiz', 'ㅊ ㄹ ㄱㄷ ㅎ ㄱㅇㅂㅌ', '천 리 길도 한 걸음부터', '{"category":"속담","hint":"큰일도 작은 시작에서 비롯된다"}'),
  ('chosung-quiz', 'ㅌㄲ ㅁㅇ ㅌㅅ', '티끌 모아 태산', '{"category":"속담","hint":"작은 것도 모이면 크게 된다"}'),
  ('chosung-quiz', 'ㅎㄴㅇ ㅁㄴㅈㄷ ㅅㅇㄴ ㄱㅁㅇ ㅇㄷ', '하늘이 무너져도 솟아날 구멍이 있다', '{"category":"속담","hint":"아무리 힘들어도 빠져나갈 방법은 있다"}'),
  ('chosung-quiz', 'ㅎㄹㅇㄷ ㅈ ㅁ ㅎㅁ ㅇㄷ', '호랑이도 제 말 하면 온다', '{"category":"속담","hint":"이야기하던 사람이 마침 나타남"}'),
  ('chosung-quiz', 'ㄱㄹ ㅆㅇㅇ ㅅㅇ ㄷ ㅌㅈㄷ', '고래 싸움에 새우 등 터진다', '{"category":"속담","hint":"센 쪽끼리 싸우는데 약한 쪽이 피해를 본다"}'),
  ('chosung-quiz', 'ㄴㅇㅅ ㄸ ㅁㄱ', '누워서 떡 먹기', '{"category":"속담","hint":"아주 쉬운 일"}'),
  ('chosung-quiz', 'ㅅㅇ ㅈ ㅁㄱ', '식은 죽 먹기', '{"category":"속담","hint":"뜨겁지 않아 후루룩 — 거리낌 없이 쉬운 일"}'),
  ('chosung-quiz', 'ㄱㄱㅅㄷ ㅅㅎㄱ', '금강산도 식후경', '{"category":"속담","hint":"아무리 좋은 구경도 배가 불러야 한다"}'),
  ('chosung-quiz', 'ㅂ ㅅㄹㄱ ㅇㄹㅎㄷ', '빈 수레가 요란하다', '{"category":"속담","hint":"실속 없는 사람이 더 떠든다"}'),
  ('chosung-quiz', 'ㅇㅁ ㅇ ㄱㄱㄹ', '우물 안 개구리', '{"category":"속담","hint":"넓은 세상을 모르는 사람"}'),
  ('chosung-quiz', 'ㄲ ㅁㄱ ㅇ ㅁㄱ', '꿩 먹고 알 먹고', '{"category":"속담","hint":"한 번에 두 가지 이득"}'),
  ('chosung-quiz', 'ㄱㅈㄴ ㄱ ㅍ', '가재는 게 편', '{"category":"속담","hint":"비슷한 처지끼리 편을 든다"}'),
  ('chosung-quiz', 'ㄷㄷㄹㄷ ㄷㄷㄱ ㅂㄱ ㄱㄴㄹ', '돌다리도 두들겨 보고 건너라', '{"category":"속담","hint":"잘 아는 일도 조심해서 하라"}'),
  ('chosung-quiz', 'ㅂㅈㅈㄷ ㅁㄷㅁ ㄴㄷ', '백지장도 맞들면 낫다', '{"category":"속담","hint":"쉬운 일도 힘을 합치면 더 쉽다"}'),
  ('chosung-quiz', 'ㅅㄱㅇ ㅁㅇㅁ ㅂㄱ ㅅㅇㄹ ㄱㄷ', '사공이 많으면 배가 산으로 간다', '{"category":"속담","hint":"참견하는 사람이 많으면 일이 엉뚱하게 흘러간다"}'),
  ('chosung-quiz', 'ㅅㅂ ㄱ ㅎㄱ', '수박 겉 핥기', '{"category":"속담","hint":"속은 모르고 겉만 건드림"}'),
  ('chosung-quiz', 'ㄱㄱㄹ ㅇㅊㅇ ㅈ ㅅㄱ ㅁ ㅎㄷ', '개구리 올챙이 적 생각 못 한다', '{"category":"속담","hint":"형편이 나아지면 어렵던 옛날을 잊는다"}'),
  ('chosung-quiz', 'ㄷㅅㅂㄹ ㄴㅁㄴ ㄸㅇㅂㅌ ㅇㅇㅂㄷ', '될성부른 나무는 떡잎부터 알아본다', '{"category":"속담","hint":"크게 될 사람은 어릴 때부터 남다르다"}'),
  ('chosung-quiz', 'ㅇㄴ ㄸ ㄱㄸㅇ ㅇㄱ ㄴㄲ', '아니 땐 굴뚝에 연기 날까', '{"category":"속담","hint":"원인 없는 결과는 없다"}'),
  ('chosung-quiz', 'ㅈㄹㅇㄷ ㅂㅇㅁ ㄲㅌㅎㄷ', '지렁이도 밟으면 꿈틀한다', '{"category":"속담","hint":"아무리 약한 사람도 업신여기면 맞선다"}');
