-- 힌트 퀴즈 시드 데이터 (직접 만든 문제 30개 — 축구선수·동물·나라·음식)
-- 힌트는 막연한 것 → 구체적인 것 순서. 이적 등으로 바뀌기 쉬운 정보(현 소속팀 등)는 쓰지 않는다.
-- 여러 번 실행해도 결과가 같도록 이 파일의 문제만 지우고 다시 넣는다. (점수 기록은 유지)
-- 위키데이터로 자동 생성한 축구선수 문제(meta.source = wikidata)는 hint-quiz-football.sql 이 따로 관리한다.
-- 적용: pnpm db:seed:local (seeds/*.sql 전체가 파일명 순서대로 적용됨)

INSERT OR IGNORE INTO game (id, name, category) VALUES ('hint-quiz', '힌트 퀴즈', 'quiz');

DELETE FROM quiz_item WHERE game_id = 'hint-quiz' AND json_extract(meta, '$.source') IS NULL;

INSERT INTO quiz_item (game_id, question, answer, meta) VALUES
  ('hint-quiz', '이 축구선수는 누구일까요?', '손흥민', '{"category": "축구선수", "hints": [{"label": "포지션", "value": "공격수"}, {"label": "국적", "value": "대한민국"}, {"label": "신장", "value": "183cm"}, {"label": "주로 쓰는 발", "value": "양발"}, {"label": "대표 경력", "value": "토트넘에서 10년 활약, 2021-22 프리미어리그 득점왕"}], "aliases": ["쏘니", "son", "손흥민선수"]}'),
  ('hint-quiz', '이 축구선수는 누구일까요?', '리오넬 메시', '{"category": "축구선수", "hints": [{"label": "포지션", "value": "공격수"}, {"label": "국적", "value": "아르헨티나"}, {"label": "신장", "value": "170cm"}, {"label": "주로 쓰는 발", "value": "왼발"}, {"label": "대표 경력", "value": "FC 바르셀로나의 전설, 2022 월드컵 우승 주장"}], "aliases": ["메시", "messi"]}'),
  ('hint-quiz', '이 축구선수는 누구일까요?', '크리스티아누 호날두', '{"category": "축구선수", "hints": [{"label": "포지션", "value": "공격수"}, {"label": "국적", "value": "포르투갈"}, {"label": "신장", "value": "187cm"}, {"label": "별명", "value": "CR7"}, {"label": "트레이드마크", "value": "\"호우(Siu)!\" 골 세리머니"}], "aliases": ["호날두", "ronaldo", "cr7"]}'),
  ('hint-quiz', '이 축구선수는 누구일까요?', '박지성', '{"category": "축구선수", "hints": [{"label": "포지션", "value": "미드필더"}, {"label": "국적", "value": "대한민국"}, {"label": "신장", "value": "178cm"}, {"label": "별명", "value": "산소탱크"}, {"label": "대표 경력", "value": "맨체스터 유나이티드, 2002 월드컵 포르투갈전 결승골"}], "aliases": ["박지성선수"]}'),
  ('hint-quiz', '이 축구선수는 누구일까요?', '차범근', '{"category": "축구선수", "hints": [{"label": "포지션", "value": "공격수"}, {"label": "국적", "value": "대한민국"}, {"label": "전성기", "value": "1970~80년대"}, {"label": "활약 리그", "value": "독일 분데스리가 (프랑크푸르트·레버쿠젠)"}, {"label": "별명", "value": "차붐"}], "aliases": ["차붐"]}'),
  ('hint-quiz', '이 축구선수는 누구일까요?', '킬리안 음바페', '{"category": "축구선수", "hints": [{"label": "포지션", "value": "공격수"}, {"label": "국적", "value": "프랑스"}, {"label": "출생", "value": "1998년"}, {"label": "대표 기록", "value": "19살에 2018 월드컵 우승"}, {"label": "결정적 힌트", "value": "2022 월드컵 결승전 해트트릭"}], "aliases": ["음바페", "mbappe"]}'),
  ('hint-quiz', '이 축구선수는 누구일까요?', '엘링 홀란', '{"category": "축구선수", "hints": [{"label": "포지션", "value": "공격수"}, {"label": "국적", "value": "노르웨이"}, {"label": "신장", "value": "190cm 중반"}, {"label": "출생", "value": "2000년"}, {"label": "대표 기록", "value": "맨체스터 시티, 프리미어리그 한 시즌 최다 36골 (2022-23)"}], "aliases": ["홀란", "홀란드", "엘링홀란드", "haaland"]}'),
  ('hint-quiz', '이 축구선수는 누구일까요?', '김민재', '{"category": "축구선수", "hints": [{"label": "포지션", "value": "수비수"}, {"label": "국적", "value": "대한민국"}, {"label": "신장", "value": "190cm"}, {"label": "별명", "value": "괴물"}, {"label": "대표 경력", "value": "나폴리에서 세리에A 우승 (2022-23), 이후 바이에른 뮌헨"}], "aliases": ["김민재선수"]}'),
  ('hint-quiz', '이 동물은 무엇일까요?', '기린', '{"category": "동물", "hints": [{"label": "분류", "value": "포유류"}, {"label": "사는 곳", "value": "아프리카 초원"}, {"label": "먹이", "value": "나뭇잎 (초식)"}, {"label": "특징", "value": "검푸른 혀가 50cm 가까이 된다"}, {"label": "결정적 힌트", "value": "세상에서 키가 가장 큰 동물"}], "aliases": ["giraffe"]}'),
  ('hint-quiz', '이 동물은 무엇일까요?', '펭귄', '{"category": "동물", "hints": [{"label": "분류", "value": "조류"}, {"label": "사는 곳", "value": "대부분 남반구의 추운 바다"}, {"label": "특징", "value": "날지 못하지만 수영을 아주 잘한다"}, {"label": "걸음걸이", "value": "뒤뚱뒤뚱"}, {"label": "결정적 힌트", "value": "턱시도를 입은 듯한 검은색·흰색 몸"}], "aliases": ["penguin"]}'),
  ('hint-quiz', '이 동물은 무엇일까요?', '캥거루', '{"category": "동물", "hints": [{"label": "분류", "value": "포유류"}, {"label": "사는 곳", "value": "호주"}, {"label": "이동 방법", "value": "두 발로 껑충껑충 뛴다"}, {"label": "특징", "value": "굵은 꼬리로 균형을 잡는다"}, {"label": "결정적 힌트", "value": "새끼를 배 주머니에 넣고 다닌다"}], "aliases": ["kangaroo"]}'),
  ('hint-quiz', '이 동물은 무엇일까요?', '문어', '{"category": "동물", "hints": [{"label": "사는 곳", "value": "바다"}, {"label": "특징", "value": "뼈가 없다"}, {"label": "놀라운 사실", "value": "심장이 3개, 피가 파란색"}, {"label": "방어 방법", "value": "먹물을 뿜는다"}, {"label": "결정적 힌트", "value": "다리가 8개"}], "aliases": ["octopus"]}'),
  ('hint-quiz', '이 동물은 무엇일까요?', '박쥐', '{"category": "동물", "hints": [{"label": "분류", "value": "포유류"}, {"label": "활동 시간", "value": "밤"}, {"label": "특징", "value": "초음파로 주변을 알아낸다"}, {"label": "자는 자세", "value": "거꾸로 매달려서 잔다"}, {"label": "결정적 힌트", "value": "하늘을 날 수 있는 유일한 포유류"}], "aliases": ["bat"]}'),
  ('hint-quiz', '이 동물은 무엇일까요?', '코알라', '{"category": "동물", "hints": [{"label": "분류", "value": "포유류 (유대류)"}, {"label": "사는 곳", "value": "호주"}, {"label": "먹이", "value": "유칼립투스 잎"}, {"label": "특징", "value": "하루 약 20시간을 잔다"}, {"label": "결정적 힌트", "value": "나무에 매달려 사는 회색 털의 동물"}], "aliases": ["koala"]}'),
  ('hint-quiz', '이 동물은 무엇일까요?', '카멜레온', '{"category": "동물", "hints": [{"label": "분류", "value": "파충류"}, {"label": "특징", "value": "두 눈을 따로따로 움직인다"}, {"label": "사냥 방법", "value": "길고 끈끈한 혀를 쏜다"}, {"label": "사는 곳", "value": "주로 아프리카·마다가스카르"}, {"label": "결정적 힌트", "value": "몸 색깔을 바꿀 수 있다"}], "aliases": ["chameleon"]}'),
  ('hint-quiz', '이 동물은 무엇일까요?', '북극곰', '{"category": "동물", "hints": [{"label": "분류", "value": "포유류"}, {"label": "사는 곳", "value": "북극"}, {"label": "놀라운 사실", "value": "피부는 검은색, 털은 투명하다"}, {"label": "먹이", "value": "주로 물범"}, {"label": "결정적 힌트", "value": "하얀 털의 커다란 곰"}], "aliases": ["흰곰", "백곰", "polarbear"]}'),
  ('hint-quiz', '이 나라는 어디일까요?', '이집트', '{"category": "나라", "hints": [{"label": "대륙", "value": "아프리카"}, {"label": "강", "value": "나일강"}, {"label": "수도", "value": "카이로"}, {"label": "유명한 것", "value": "미라"}, {"label": "결정적 힌트", "value": "피라미드와 스핑크스"}], "aliases": ["egypt"]}'),
  ('hint-quiz', '이 나라는 어디일까요?', '일본', '{"category": "나라", "hints": [{"label": "대륙", "value": "아시아"}, {"label": "지형", "value": "섬나라"}, {"label": "수도", "value": "도쿄"}, {"label": "유명한 음식", "value": "초밥, 라멘"}, {"label": "결정적 힌트", "value": "후지산"}], "aliases": ["japan"]}'),
  ('hint-quiz', '이 나라는 어디일까요?', '브라질', '{"category": "나라", "hints": [{"label": "대륙", "value": "남아메리카"}, {"label": "언어", "value": "포르투갈어"}, {"label": "자연", "value": "아마존 열대우림"}, {"label": "축구", "value": "월드컵 최다 우승국 (5회)"}, {"label": "결정적 힌트", "value": "삼바와 리우 카니발"}], "aliases": ["brazil"]}'),
  ('hint-quiz', '이 나라는 어디일까요?', '이탈리아', '{"category": "나라", "hints": [{"label": "대륙", "value": "유럽"}, {"label": "지도 모양", "value": "장화처럼 생겼다"}, {"label": "수도", "value": "로마"}, {"label": "유명한 음식", "value": "피자, 파스타"}, {"label": "결정적 힌트", "value": "피사의 사탑, 콜로세움"}], "aliases": ["italy"]}'),
  ('hint-quiz', '이 나라는 어디일까요?', '호주', '{"category": "나라", "hints": [{"label": "대륙", "value": "오세아니아"}, {"label": "수도", "value": "캔버라 (시드니가 아님!)"}, {"label": "계절", "value": "한국과 반대 — 12월이 여름"}, {"label": "동물", "value": "캥거루, 코알라"}, {"label": "결정적 힌트", "value": "시드니 오페라 하우스"}], "aliases": ["오스트레일리아", "australia"]}'),
  ('hint-quiz', '이 나라는 어디일까요?', '프랑스', '{"category": "나라", "hints": [{"label": "대륙", "value": "유럽"}, {"label": "국기", "value": "파랑·하양·빨강 세로 줄무늬"}, {"label": "유명한 음식", "value": "바게트, 크루아상"}, {"label": "수도", "value": "파리"}, {"label": "결정적 힌트", "value": "에펠탑"}], "aliases": ["france"]}'),
  ('hint-quiz', '이 나라는 어디일까요?', '인도', '{"category": "나라", "hints": [{"label": "대륙", "value": "아시아"}, {"label": "인구", "value": "세계 1위 (2023년~)"}, {"label": "유명한 음식", "value": "카레, 난"}, {"label": "수도", "value": "뉴델리"}, {"label": "결정적 힌트", "value": "타지마할"}], "aliases": ["india"]}'),
  ('hint-quiz', '이 나라는 어디일까요?', '캐나다', '{"category": "나라", "hints": [{"label": "대륙", "value": "북아메리카"}, {"label": "언어", "value": "영어와 프랑스어"}, {"label": "수도", "value": "오타와"}, {"label": "특산물", "value": "메이플 시럽"}, {"label": "결정적 힌트", "value": "국기에 빨간 단풍잎"}], "aliases": ["canada"]}'),
  ('hint-quiz', '이 음식은 무엇일까요?', '김치', '{"category": "음식", "hints": [{"label": "나라", "value": "한국"}, {"label": "조리 방법", "value": "발효시킨다"}, {"label": "주재료", "value": "배추"}, {"label": "색깔", "value": "빨간색"}, {"label": "결정적 힌트", "value": "겨울이 오기 전 김장"}], "aliases": ["kimchi"]}'),
  ('hint-quiz', '이 음식은 무엇일까요?', '짜장면', '{"category": "음식", "hints": [{"label": "파는 곳", "value": "중국집"}, {"label": "종류", "value": "면 요리"}, {"label": "색깔", "value": "검은색"}, {"label": "먹는 날", "value": "이삿날의 단골 메뉴"}, {"label": "결정적 힌트", "value": "춘장으로 만든 소스"}], "aliases": ["자장면"]}'),
  ('hint-quiz', '이 음식은 무엇일까요?', '피자', '{"category": "음식", "hints": [{"label": "시작된 나라", "value": "이탈리아"}, {"label": "모양", "value": "둥글다"}, {"label": "먹는 방법", "value": "조각으로 나눠 먹는다"}, {"label": "주재료", "value": "밀가루 도우와 치즈"}, {"label": "결정적 힌트", "value": "페퍼로니, 하와이안"}], "aliases": ["pizza"]}'),
  ('hint-quiz', '이 음식은 무엇일까요?', '떡국', '{"category": "음식", "hints": [{"label": "나라", "value": "한국"}, {"label": "먹는 날", "value": "설날"}, {"label": "주재료", "value": "가래떡을 얇게 썬 것"}, {"label": "종류", "value": "국물 요리"}, {"label": "결정적 힌트", "value": "한 그릇 먹으면 한 살 더 먹는다"}]}'),
  ('hint-quiz', '이 음식은 무엇일까요?', '초밥', '{"category": "음식", "hints": [{"label": "나라", "value": "일본"}, {"label": "주재료", "value": "식초로 간한 밥"}, {"label": "곁들이는 것", "value": "와사비, 간장"}, {"label": "식당", "value": "회전하는 벨트 위로 나오기도 한다"}, {"label": "결정적 힌트", "value": "밥 위에 생선회를 얹는다"}], "aliases": ["스시", "sushi"]}'),
  ('hint-quiz', '이 음식은 무엇일까요?', '삼계탕', '{"category": "음식", "hints": [{"label": "나라", "value": "한국"}, {"label": "먹는 날", "value": "여름 복날"}, {"label": "주재료", "value": "닭 한 마리"}, {"label": "속 재료", "value": "인삼, 찹쌀, 대추"}, {"label": "결정적 힌트", "value": "뚝배기에 담긴 보양식"}]}');
